apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-sm
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets # Name of the service account used by ESO
            namespace: default
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-postgres-db-credentials
  namespace: default
spec:
  secretStoreRef:
    name: aws-sm
    kind: SecretStore
  target:
    name: postgres-db-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: postgres-db-credentials
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-aws-credentials
  namespace: default
spec:
  secretStoreRef:
    name: aws-sm
    kind: SecretStore
  target:
    name: aws-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: aws-credentials
