apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-mlflow-tracking
  namespace: default
spec:
  secretStoreRef:
    name: aws-sm
    kind: SecretStore
  target:
    name: mlflow-tracking
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: mlflow-tracking
