apiVersion: v1
kind: Service
metadata:
  name: mlflow-inference-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: mlflow-inference
  ports:
    - name: http
      port: 8000
      targetPort: 8000
